#ddev-generated
hooks:
  post-start:
    - exec: "mkdir -p /var/www/html/.ddev/.opencode"
    - exec: "touch /var/www/html/.ddev/.opencode/opencode.jsonc"
    - exec: "ln -sf /var/www/html/.ddev/.opencode/opencode.jsonc ~/opencode.jsonc"
    - exec: "ln -sf /var/www/html/.ddev/.opencode ~/.opencode"
    - exec: "if [ -f ~/CLAUDE.md ]; then ln -sf ~/CLAUDE.md ~/AGENTS.md; fi"
