#ddev-generated
hooks:
  post-start:
    - exec: ">> /var/www/html/.ddev/.opencode/opencode.jsonc && ln -s /var/www/html/.ddev/.opencode/opencode.jsonc ~/opencode.jsonc"
    - exec: "mkdir -p /var/www/html/.ddev/.opencode && ln -s /var/www/html/.ddev/.opencode ~/.opencode"
